--Chris Edgeworth
-- SQL statements generated by parsing the csv file: filers.csv
-- using field: committeeStatusCd
-- to populate table: codes_committee_status
-- Generated on 2026-02-29
-- 
DROP TABLE IF EXISTS codes_committee_status;
CREATE TABLE codes_committee_status (
        committeeStatusCd  text PRIMARY KEY,
        committeeStatusCd_name  text
);

INSERT INTO codes_committee_status( committeeStatusCd, committeeStatusCd_name )
VALUES
( 'ACTIVE',  'Active' ),
( 'TERMINATED',  'Terminated' ),
( 'INACTIVE',  'Inactive' );

-- SQL statements generated by parsing the csv file: cover.csv
-- also used in TEC_LA_CSV
-- using field: sourceCategoryCd
-- to populate table: codes_source_category
-- Generated on 2026-02-29
-- 
DROP TABLE IF EXISTS codes_source_category;
CREATE TABLE codes_source_category (
	sourceCategoryCd  text PRIMARY KEY,
	sourceCategoryCd_name  text
);

INSERT INTO codes_source_category( sourceCategoryCd, sourceCategoryCd_name )
VALUES
( 'ELECTRONIC',  'Electronic' ),
( 'KEYED',  'Keyed' );


-- SQL statements generated by parsing the csv file: loans.csv
-- using field: loanStatusCd
-- to populate table: codes_loan_status
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_loan_status;
CREATE TABLE codes_loan_status (
        loanStatusCd  text PRIMARY KEY,
        loanStatusCd_name  text
);

INSERT INTO codes_loan_status( loanStatusCd, loanStatusCd_name )
VALUES
( 'RPTUNPAID',  'Rptunpaid' ),
( 'RPTPAID',  'Rptpaid' ),
( '1STRPT',  '1strpt' );


-- SQL statements generated by parsing the csv file: spacs.csv
-- using field: spacPositionCd
-- to populate table: codes_position
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_position;
CREATE TABLE codes_position (
        spacPositionCd  text PRIMARY KEY,
        spacPositionCd_name  text
);

INSERT INTO codes_position( spacPositionCd, spacPositionCd_name )
VALUES
( 'SUPPORT',  'Support' ),
( 'OPPOSE',  'Oppose' ),
( 'ASSIST',  'Assist' );

-- SQL statements generated by parsing the csv file: travel.csv
-- using field: transportationTypeCd
-- to populate table: codes_transportation_type
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_transportation_type;
CREATE TABLE codes_transportation_type (
        transportationTypeCd  text PRIMARY KEY,
        transportationTypeCd_name  text
);

INSERT INTO codes_transportation_type( transportationTypeCd, transportationTypeCd_name )
VALUES
( 'PRIVAUTO',  'Private auto' ),
( 'COMMAUTO',  'Commercial auto' ),
( 'COMMAIR',  'Commercial air' ),
( 'OTHER',  'Other' ),
( 'RAIL',  'Rail' ),
( 'PRIVAIR',  'Private air' ),
( 'COMMBOAT',  'Commercial boat' ),
( 'BAGFEES',  'Baggage fees' );

-- SQL statements generated by parsing the csv file: notices.csv
-- using field: notifierCommactPersentKindCd
-- to populate table: codes_person_kind
-- Generated on 2026-02-17
-- person or entity kind code for lobby activity reports, e.g. GPAC support, SPAC support
DROP TABLE IF EXISTS codes_persent_kind;
CREATE TABLE codes_persent_kind (
        persentKindCd  text PRIMARY KEY,
        persentKindCd_name  text
);

INSERT INTO codes_persent_kind( persentKindCd, persentKindCd_name )
VALUES
( 'GPACSUPPORT',  'GPAC support' ),
( 'SPACSUPPORT',  'SPAC support' );

-- SQL statements generated by parsing the csv file: purpose.csv
-- using field: subjectCategoryCd
-- to populate table: codes_subject_category
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_subject_category;
CREATE TABLE codes_subject_category (
        subjectCategoryCd  text PRIMARY KEY,
        subjectCategoryCd_name  text
);

INSERT INTO codes_subject_category( subjectCategoryCd, subjectCategoryCd_name )
VALUES
( 'OFFICE',  'Office' ),
( 'CANDIDATE',  'Candidate' ),
( 'CANDIDATEP',  'Candidatep' ),
( 'OFFICEPOL',  'Officepol' ),
( 'MEASURE',  'Measure' );



-- SQL statements generated by parsing the csv file: purpose.csv
-- using field: subjectPositionCd
-- to populate table: codes_subject_position
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_subject_position;
CREATE TABLE codes_subject_position (
        subjectPositionCd  text PRIMARY KEY,
        subjectPositionCd_name  text
);

INSERT INTO codes_subject_position( subjectPositionCd, subjectPositionCd_name )
VALUES
( 'OPPOSE',  'Oppose' ),
( 'SUPPORT',  'Support' ),
( 'ASSIST',  'Assist' );


--TEC_LA_CSV
-- SQL statements generated by parsing the csv file: ../data/TEC_LA_CSV/LaSub.csv
-- using field: subjectMatterCd
-- to populate table: codes_subject_matter
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_subject_matter;
CREATE TABLE codes_subject_matter (
        subjectMatterCd  text PRIMARY KEY,
        subjectMatterCd_name  text
);

INSERT INTO codes_subject_matter( subjectMatterCd, subjectMatterCd_name )
VALUES
( '31',  '31' ),
( '98',  '98' ),
( '47',  '47' ),
( '28',  '28' ),
( '83',  '83' ),
( '27',  '27' ),
( '26',  '26' ),
( '57',  '57' ),
( '17',  '17' ),
( '12',  '12' ),
( '33',  '33' ),
( '36',  '36' ),
( '65',  '65' ),
( '68',  '68' ),
( '67',  '67' ),
( '66',  '66' ),
( '23',  '23' ),
( '74',  '74' ),
( '99',  '99' ),
( '06',  '06' ),
( '43',  '43' ),
( '40',  '40' ),
( '78',  '78' ),
( '22',  '22' ),
( '80',  '80' ),
( '37',  '37' ),
( '59',  '59' ),
( '71',  '71' ),
( '84',  '84' ),
( '44',  '44' ),
( '25',  '25' ),
( '61',  '61' ),
( '58',  '58' ),
( '24',  '24' ),
( '04',  '04' ),
( '35',  '35' ),
( '50',  '50' ),
( '34',  '34' ),
( '08',  '08' ),
( '11',  '11' ),
( '29',  '29' ),
( '53',  '53' ),
( '70',  '70' ),
( '54',  '54' ),
( '20',  '20' ),
( '09',  '09' ),
( '38',  '38' ),
( '46',  '46' ),
( '16',  '16' ),
( '62',  '62' ),
( '52',  '52' ),
( '13',  '13' ),
( '39',  '39' ),
( '42',  '42' ),
( '18',  '18' ),
( '81',  '81' ),
( '63',  '63' ),
( '19',  '19' ),
( '41',  '41' ),
( '01',  '01' ),
( '77',  '77' ),
( '79',  '79' ),
( '15',  '15' ),
( '14',  '14' ),
( '21',  '21' ),
( '32',  '32' ),
( '76',  '76' ),
( '45',  '45' ),
( '56',  '56' ),
( '30',  '30' ),
( '72',  '72' ),
( '02',  '02' ),
( '75',  '75' ),
( '64',  '64' ),
( '51',  '51' ),
( '55',  '55' ),
( '82',  '82' ),
( '10',  '10' ),
( '69',  '69' ),
( '73',  '73' ),
( '49',  '49' ),
( '07',  '07' ),
( '60',  '60' ),
( '03',  '03' ),
( '48',  '48' ),
( '05',  '05' );

-- SQL statements generated by parsing the csv file: ../data/TEC_LA_CSV/LaTran.csv
-- using field: lobbyActivityPeriodCd
-- to populate table: codes_lobby_activity_period
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_lobby_activity_period;
CREATE TABLE codes_lobby_activity_period (
        lobbyActivityPeriodCd  text PRIMARY KEY,
        lobbyActivityPeriodCd_name  text
);

INSERT INTO codes_lobby_activity_period( lobbyActivityPeriodCd, lobbyActivityPeriodCd_name )
VALUES
( 'NOVEMBER',  'November' ),
( 'MARCH',  'March' ),
( 'OCTOBER',  'October' ),
( 'MAY',  'May' ),
( 'SEPTEMBER',  'September' ),
( 'FEBRUARY',  'February' ),
( 'DECEMBER',  'December' ),
( 'APRIL',  'April' ),
( 'JUNE',  'June' ),
( 'AUGUST',  'August' ),
( 'JANUARY',  'January' ),
( 'ANNUAL',  'Annual' ),
( 'JULY',  'July' );

-- SQL statements generated by parsing the csv file: ../data/TEC_LA_CSV/LaFood.csv
-- using field: activityAmountCd
-- to populate table: codes_activity_amount
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_activity_amount;
CREATE TABLE codes_activity_amount (
        activityAmountCd  text PRIMARY KEY,
        activityAmountCd_name  text
);

INSERT INTO codes_activity_amount( activityAmountCd, activityAmountCd_name )
VALUES
( 'LT450',  'Lt450' ),
( 'LT350',  'Lt350' ),
( 'LT200',  'Lt200' ),
( 'LT400',  'Lt400' ),
( 'LT500',  'Lt500' ),
( 'OTHER',  'Other' ),
( 'LT250',  'Lt250' ),
( 'LT150',  'Lt150' ),
( 'LT300',  'Lt300' ),
( 'LT100',  'Lt100' );


-- SQL statements generated by parsing the csv file: ../data/TEC_LA_CSV/LaEvnt.csv
-- using field: lobbyEventKindCd
-- to populate table: codes_lobby_event_kind
-- Generated on 2026-02-17
-- 
DROP TABLE IF EXISTS codes_lobby_event_kind;
CREATE TABLE codes_lobby_event_kind (
        lobbyEventKindCd  text PRIMARY KEY,
        lobbyEventKindCd_name  text
);

INSERT INTO codes_lobby_event_kind( lobbyEventKindCd, lobbyEventKindCd_name )
VALUES
( 'CHARITY',  'Charity' ),
( 'FUNDRAISER',  'Fundraiser' );