DROP TABLE IF EXISTS codes_name_suffixes;

CREATE TABLE codes_name_suffixes (
	suffix_code  text PRIMARY KEY,
	suffix_name  text
);

INSERT INTO codes_name_suffixes( suffix_code, suffix_name )
VALUES
	( 'AUD',   'Au.D' ),
	( 'CDT',   'C.D.T' ),
	( 'CPA',   'CPA' ),
	( 'DC',    'D.C.' ),
	( 'DDS',   'D.D.S' ),
	( 'DJ',    'DJ' ),
	( 'DMD',   'DMD' ),
	( 'DO',    'D.O.' ),
	( 'DPM',   'DPM' ),
	( 'DRPH',  'DrPH' ),
	( 'DSN',   'DSN' ),
	( 'DVM',   'DVM' ),
	( 'EDD',   'Ed.D.' ),
	( 'ESQ',   'Esq.' ),
	( 'I',     'I' ),
	( 'II',    'II' ),
	( 'III',   'III' ),
	( 'IV',    'IV' ),
	( 'JD',    'J.D.' ),
	( 'JR',    'Jr.' ),
	( 'JRMD',  'Jr MD' ),
	( 'LAC',   'L.AC.' ),
	( 'LLB',   'LLB' ),
	( 'LLC',   'LLC' ),
	( 'LMSW',  'LMSW' ),
	( 'LVN',   'LVN' ),
	( 'MA',    'M.A.' ),
	( 'MBA',   'MBA' ),
	( 'MD',    'M.D.' ),
	( 'MDDDS', 'MDDDS' ),
	( 'MDMS',  'MD MS' ),
	( 'MDPHD', 'MDPhD' ),
	( 'MED',   'M.Ed.' ),
	( 'MHA',   'MHA' ),
	( 'MPS',   'MPS' ),
	( 'OD',    'O.D.' ),
	( 'PA',    'P.A.' ),
	( 'PAC',   'PA-C' ),
	( 'PC',    'P.C.' ),
	( 'PE',    'P.E.' ),
	( 'PG',    'P.G.' ),
	( 'PHD',   'Ph.D' ),
	( 'PT',    'P.T.' ),
	( 'RDH',   'RDH' ),
	( 'RET',   'Ret.' ),
	( 'RN',    'R.N.' ),
	( 'RPH',   'R.Ph.' ),
	( 'SR',    'Sr.' ),
	( 'V',     'V' ),
	( 'VI',    'VI' )
;
