DROP TABLE IF EXISTS tec.codes_forms;

CREATE TABLE tec.codes_forms (
	form_id          text PRIMARY KEY,
	schedule         bool,
	form_name        text,
	report_name      text,
	form_description text
);
INSERT INTO tec.codes_forms
VALUES
	( 'BRSSPK'            ,  'N', 'BRSSPK'             ,'Candidate For Speaker Of The Texas House Of Representatives: Statement Of Contributions, Loans And Expenditures' ),
	( 'BSSSPK'            ,  'N', 'BSSSPK'             ,'Candidate For Speaker Of The Texas House Of Representatives: Statement Of Contributions, Loans And Expenditures' ),
	( 'COHFR'             ,  'N', 'C/OH-FR'            ,'Candidate/Officeholder Designation Of Final Report' ),
	( 'COHSS'             ,  'N', 'C/OH-SS'            ,'Candidate/Officeholder Special Session Report' ),
	( 'CORCOH'            ,  'N', 'COR-C/OH'           ,'Correction Affidavit For Candidate/Officeholder' ),
	( 'CORDAILYCCOH'      ,  'N', 'COR-DAILY-C C/OH'   ,'Correction Affidavit For Candidate/Officeholder Daily Pre-Election Report' ),
	( 'CORDAILYCPAC'      ,  'N', 'COR-DAILY-C PAC'    ,'Correction Affidavit For Daily Pre-Election Report Of Contributions' ),
	( 'CORDAILYEPAC'      ,  'N', 'COR-DAILY-E PAC'    ,'Correction Affidavit For Daily Pre-Election Report Of Direct Expenditures' ),
	( 'CORLEG'            ,  'N', 'COR-LEG'            ,'Correction Affidavit For Legislative Caucus' ),
	( 'CORLOBBYACT'       ,  'N', 'COR-LOBBYACT'       ,'Corrected Lobby Activities Report' ),
	( 'CORLOBBYREG'       ,  'N', 'COR-LOBBYREG'       ,'Corrected Form REG' ),
	( 'CORPAC'            ,  'N', 'COR-PAC'            ,'Correction Affidavit For Political Committee' ),
	( 'CORPFS'            ,  'N', 'COR-PFS'            ,'Corrected Financial Statement and Good Faith Affidavit' ),
	( 'CORPTY'            ,  'N', 'COR-PTY'            ,'Correction Affidavit For Political Party Report Regarding Funds From Corporations And Labor Organizations' ),
	( 'CORSPK'            ,  'N', 'COR-SPK'            ,'Correction Affidavit For Candidate For Speaker Of The Texas House Of Representatives' ),
	( 'DAILYCCOH'         ,  'N', 'DAILY-C COH'        ,'Candidate/Officeholder Daily Pre-Election Report Of Contributions' ),
	( 'DAILYCPAC'         ,  'N', 'DAILY-C PAC'        ,'Political Committee Daily Pre-Election Report Of Contributions' ),
	( 'DAILYEPAC'         ,  'N', 'DAILY-E PAC'        ,'Political Committee Daily Pre-Election Report Of Expenditures' ),
	( 'DIRE'              ,  'N', 'DIR-E'              ,'Daily Pre-Election Report Of Direct Expenditures' ),
	( 'JSPACDR'           ,  'N', 'JSPAC-DR'           ,'Judicial Specific-Purpose Committee Report: Affidavit Of Dissolution' ),
	( 'LEG'               ,  'N', 'LEG'                ,'Legislative Caucus Report Of Contributions And Expenditures' ),
	( 'PACDR'             ,  'N', 'PAC-DR'             ,'Political Committee Affidavit Of Dissolution' ),
	( 'SCCOHFR'           ,  'N', 'SC C/OH-FR'         ,'State/County Chair Candidate/Officeholder Designation of Final Report' ),
	( 'SCSPACDR'          ,  'N', 'SC SPAC-DR'         ,'State/County Chair Report:  Designation Of Final Report' ),
	( 'SPK'               ,  'N', 'SPK'                ,'Candidate For Speaker Of The Texas House Of Representatives: Statement Of Contributions, Loans And Expenditures' ),
	( 'SPKJAN'            ,  'N', 'SPKJAN'             ,'Candidate For Speaker Of The Texas House Of Representatives: Statement Of Contributions, Loans And Expenditures' ),
	( 'SPKJUL'            ,  'N', 'SPKJUL'             ,'Candidate For Speaker Of The Texas House Of Representatives: Statement Of Contributions, Loans And Expenditures' ),
	( 'SPKMAR'            ,  'N', 'SPKMAR'             ,'Candidate For Speaker Of The Texas House Of Representatives: Statement Of Contributions, Loans And Expenditures' ),
	( 'SPKMAY'            ,  'N', 'SPKMAY'             ,'Candidate For Speaker Of The Texas House Of Representatives: Statement Of Contributions, Loans And Expenditures' ),
	( 'SPKNOV'            ,  'N', 'SPKNOV'             ,'Candidate For Speaker Of The Texas House Of Representatives: Statement Of Contributions, Loans And Expenditures' ),
	( 'SPKSEP'            ,  'N', 'SPKSEP'             ,'Candidate For Speaker Of The Texas House Of Representatives: Statement Of Contributions, Loans And Expenditures' ),
	( 'SPKUC'             ,  'N', 'SPKUC'              ,'Former Candidate For Speaker Of The Texas House Of Representatives: Annual Report Of Unexpended Contributions' ),
	( 'A1'                ,  'Y', 'A1'                 ,'Monetary Political Contributions' ),
	( 'A2'                ,  'Y', 'A2'                 ,'Non-Monetary (In-Kind) Political Contributions' ),
	( 'AJ1'               ,  'Y', 'A(J)1'              ,'Monetary Political Contributions (Judicial)' ),
	( 'AL'                ,  'Y', 'A(L)'               ,'Non-Caucus Member Contributions' ),
	( 'ALC'               ,  'Y', 'A(L)C'              ,'Contributions from Caucus Members' ),
	( 'AS1'               ,  'Y', 'A(S)1'              ,'Monetary Contributions (Speaker)' ),
	( 'AS2'               ,  'Y', 'A(S)2'              ,'In-Kind Contributions (Speaker)' ),
	( 'B'                 ,  'Y', 'B'                  ,'Pledged Contributions' ),
	( 'BJ'                ,  'Y', 'B(J)'               ,'Pledged Contributions (Judicial)' ),
	( 'BSS'               ,  'Y', 'B-SS'               ,'Pledged Contributions' ),
	( 'C1'                ,  'Y', 'C1'                 ,'Monetary Contributions From Corporation Or Labor Organization' ),
	( 'C2'                ,  'Y', 'C2'                 ,'Non-Monetary (In-Kind) Contributions From Corporation Or Labor Organization' ),
	( 'C3'                ,  'Y', 'C3'                 ,'Monetary Support From Corporation Or Labor Organization' ),
	( 'C4'                ,  'Y', 'C4'                 ,'Non-Monetary Support From Corporation Or Labor Organization' ),
	( 'D'                 ,  'Y', 'D'                  ,'Pledged Contributions From Corporation Or Labor Organization' ),
	( 'E'                 ,  'Y', 'E'                  ,'Loans' ),
	( 'EJ'                ,  'Y', 'E(J)'               ,'Loans (Judicial)' ),
	( 'EL'                ,  'Y', 'E(L)'               ,'Loans To Legislative Caucus' ),
	( 'ES'                ,  'Y', 'E(S)'               ,'Loans (Speaker)' ),
	( 'F1'                ,  'Y', 'F1'                 ,'Political Expenditures From Political Contributions' ),
	( 'F2'                ,  'Y', 'F2'                 ,'Unpaid Incurred Obligations' ),
	( 'F3'                ,  'Y', 'F3'                 ,'Purchase Of Investments From Political Contributions' ),
	( 'FL'                ,  'Y', 'F(L)'               ,'Legislative Caucus Expenditures' ),
	( 'FS'                ,  'Y', 'F(S)'               ,'Expenditures (Speaker)' ),
	( 'G'                 ,  'Y', 'G'                  ,'Political Expenditures From Personal Funds' ),
	( 'H'                 ,  'Y', 'H'                  ,'Payment From Political Contributions To The Business Of A C/OH' ),
	( 'I'                 ,  'Y', 'I'                  ,'Non-Political Expenditures From Political Contributions' ),
	( 'K'                 ,  'Y', 'K'                  ,'Interest, Credits, Gains, Refunds, And Contributions Returned To Filer' ),
	( 'L'                 ,  'Y', 'L'                  ,'Outstanding Loans' ),
	( 'LOBBYACTA'         ,  'Y', 'LOBBYACTA'          ,'Subject Matter-Schedule A' ),
	( 'LOBBYACTB'         ,  'Y', 'LOBBYACTB'          ,'Transportation and Lodging-Schedule B' ),
	( 'LOBBYACTC'         ,  'Y', 'LOBBYACTC'          ,'Food and Beverages-Schedule C' ),
	( 'LOBBYACTD'         ,  'Y', 'LOBBYACTD'          ,'Entertainment-Schedule D' ),
	( 'LOBBYACTE'         ,  'Y', 'LOBBYACTE'          ,'Gifts-Schedule E' ),
	( 'LOBBYACTF'         ,  'Y', 'LOBBYACTF'          ,'Awards and Mementos-Schedule F' ),
	( 'LOBBYACTG'         ,  'Y', 'LOBBYACTG'          ,'Political Fundraisers and Charity Events-Schedule G' ),
	( 'LOBBYAREG1ADD'     ,  'Y', 'LOBBYAREG1ADD'      ,'Lobby Registration Amendment Addendum' ),
	( 'LOBBYAREGAGRP'     ,  'Y', 'LOBBYAREGAGRP'      ,'Lobby Registration Amendment Schedule A Group' ),
	( 'LOBBYAREGAPG1'     ,  'Y', 'LOBBYAREGAPG1'      ,'Lobby Registration Amendment Schedule A Pg 1- Part 1-Part 2-Part 3' ),
	( 'LOBBYAREGAPG2'     ,  'Y', 'LOBBYAREGAPG2'      ,'Lobby Registration Amendment Schedule A Pg 2- Part 3a' ),
	( 'LOBBYAREGAPG3'     ,  'Y', 'LOBBYAREGAPG3'      ,'Lobby Registration Amendment Schedule A Pg 3- Part 3b' ),
	( 'LOBBYAREGAPG4'     ,  'Y', 'LOBBYAREGAPG4'      ,'Lobby Registration Amendment Schedule A Pg 4- Part 4' ),
	( 'LOBBYAREGAPG5'     ,  'Y', 'LOBBYAREGAPG5'      ,'Lobby Registration Amendment Schedule A Pg 5- Part 5' ),
	( 'LOBBYAREGAPG6'     ,  'Y', 'LOBBYAREGAPG6'      ,'Lobby Registration Amendment Schedule A-Pg 6- Part 6' ),
	( 'LOBBYAREGB'        ,  'Y', 'LOBBYAREGB'         ,'Lobby Registration Amendment Schedule B-' ),
	( 'LOBBYAREGC'        ,  'Y', 'LOBBYAREGC'         ,'Lobby Registration Amendment Schedule C- Deletions' ),
	( 'LOBBYREG1ADD'      ,  'Y', 'LOBBYREG1ADD'       ,'Lobby Registration Addendum' ),
	( 'LOBBYREGAGRP'      ,  'Y', 'LOBBYREGAGRP'       ,'Lobby Registration Schedule A Group' ),
	( 'LOBBYREGAPG1'      ,  'Y', 'LOBBYREGAPG1'       ,'Lobby Registration Schedule A Pg 1-Part 1-Part 2- Part 3' ),
	( 'LOBBYREGAPG2'      ,  'Y', 'LOBBYREGAPG2'       ,'Lobby Registration Schedule A Pg 2-Part 3a' ),
	( 'LOBBYREGAPG3'      ,  'Y', 'LOBBYREGAPG3'       ,'Lobby Registration Schedule A Pg 3-Part 3b' ),
	( 'LOBBYREGAPG4'      ,  'Y', 'LOBBYREGAPG4'       ,'Lobby Registration Schedule A Pg 4-Part 4' ),
	( 'LOBBYREGAPG5'      ,  'Y', 'LOBBYREGAPG5'       ,'Lobby Registration Schedule A Pg 5-Part 5' ),
	( 'LOBBYREGAPG6'      ,  'Y', 'LOBBYREGAPG6'       ,'Lobby Registration Schedule A-Pg 6- Part 6' ),
	( 'LOBBYREGB'         ,  'Y', 'LOBBYREGB'          ,'Lobby Registration Schedule B- Assistant' ),
	( 'M'                 ,  'Y', 'M'                  ,'Assets Valued At $500 Or More' ),
	( 'PFSADD'            ,  'Y', 'PFSADD'             ,'Personal Financial Statement Additonal Dependent Children' ),
	( 'PFSAFF'            ,  'Y', 'PFSAFF'             ,'Personal Financial Statement Affidavit' ),
	( 'PFSPART10A'        ,  'Y', 'PFSPART10A'         ,'PFSPart 10A Blind Trusts' ),
	( 'PFSPART10B'        ,  'Y', 'PFSPART10B'         ,'PFSPart 10B Trustee Statement' ),
	( 'PFSPART11A'        ,  'Y', 'PFSPART11A'         ,'PFSPart 11A Assets of Business Associations' ),
	( 'PFSPART11B'        ,  'Y', 'PFSPART11B'         ,'PFSPart 11B Liabilities of Business Associations' ),
	( 'PFSPART12'         ,  'Y', 'PFSPART12'          ,'PFSPart 12 Boards and Executive Positions' ),
	( 'PFSPART13'         ,  'Y', 'PFSPART13'          ,'PFSPart 13 Expenses Accepted Under Honorarium Exception' ),
	( 'PFSPART14'         ,  'Y', 'PFSPART14'          ,'PFSPart 14 Interest in Business in Common With Lobbyist' ),
	( 'PFSPART15'         ,  'Y', 'PFSPART15'          ,'PFSPart 15 Fees Received for Services Rendered To a Lobbyist Or Lobbyist''s Employer' ),
	( 'PFSPART16'         ,  'Y', 'PFSPART16'          ,'PFSPart 16 Representation By Legislator Before State Agency' ),
	( 'PFSPART17'         ,  'Y', 'PFSPART17'          ,'PFSPart 17 Benefits Derived From Functions Honoring Public Servant' ),
	( 'PFSPART18'         ,  'Y', 'PFSPART18'          ,'PFSPart 18 Legislative Continuances' ),
	( 'PFSPART1A'         ,  'Y', 'PFSPART1A'          ,'PFSPart 1A Sources of Occupational Income' ),
	( 'PFSPART1B'         ,  'Y', 'PFSPART1B'          ,'PFSPart 1B Retainers' ),
	( 'PFSPART2'          ,  'Y', 'PFSPART2'           ,'PFSPart 2 Stock' ),
	( 'PFSPART3'          ,  'Y', 'PFSPART3'           ,'PFSPart 3 Bonds, Notes, and Other Commercial Paper' ),
	( 'PFSPART4'          ,  'Y', 'PFSPART4'           ,'PFSPart 4 Mutual Funds' ),
	( 'PFSPART5'          ,  'Y', 'PFSPART5'           ,'PFSPart 5 Income From Interest, Dividends, Royalties and Rents' ),
	( 'PFSPART6'          ,  'Y', 'PFSPART6'           ,'PFSPart 6 Personal Notes and Lease Agreements' ),
	( 'PFSPART7A'         ,  'Y', 'PFSPART7A'          ,'PFSPart 7A Interests In Real Property' ),
	( 'PFSPART7B'         ,  'Y', 'PFSPART7B'          ,'PFSPart 7B Interests in Business Entities' ),
	( 'PFSPART8'          ,  'Y', 'PFSPART8'           ,'PFSPart 8 Gifts' ),
	( 'PFSPART9'          ,  'Y', 'PFSPART9'           ,'PFSPart 9 Trust Income' ),
	( 'PFSPARTSNA'        ,  'Y', 'PFSPARTSNA'         ,'Parts Marked ''Not Applicable'' By Filer' ),
	( 'SPKUCFS'           ,  'Y', 'SPKUC F(S)'         ,'Expenditures (Speaker)' ),

	-- None of these are coded with ^SUBTOTALS, so let's remove it.
	-- Further, *many of these are in fact coded in the system in formtypecd fields
		( 'ASIFSPAC' ,  'Y', 'SUBTOTALS ASIFSPAC' ,'N/A' ),
		( 'CEC'      ,  'Y', 'SUBTOTALS - CEC'    ,'N/A' ),
		( 'COH'      ,  'Y', 'SUBTOTALS - C/OH'   ,'N/A' ),
		( 'DCE'      ,  'Y', 'SUBTOTALS - DCE'    ,'N/A' ),
		( 'GPAC'     ,  'Y', 'SUBTOTALS - GPAC'   ,'N/A' ),
		( 'JCOH'     ,  'Y', 'SUBTOTALS - JC/OH'  ,'N/A' ),
		( 'JSPAC'    ,  'Y', 'SUBTOTALS - JSPAC'  ,'N/A' ),
		-- That makes LEG a dupe with the above
		--( 'LEG'      ,  'Y', 'SUBTOTALS - LEG'    ,'N/A' ),
		( 'MCEC'     ,  'Y', 'SUBTOTALS - MCEC'   ,'N/A' ),
		( 'MPAC'     ,  'Y', 'SUBTOTALS - MPAC'   ,'N/A' ),
		( 'PTYCORP'  ,  'Y', 'SUBTOTALS - PTYCORP','N/A' ),
		( 'SCCOH'    ,  'Y', 'SUBTOTALS - SC C/OH','N/A' ),
		( 'SCSPAC'   ,  'Y', 'SUBTOTALS - SC SPAC','N/A' ),
		( 'SPAC'     ,  'Y', 'SUBTOTALS - SPAC'   ,'N/A' ),
		-- That makes SPK a dupe with the above
		--( 'SPK'      ,  'Y', 'SUBTOTALS - SPK'    ,'N/A' ),

	( 'T'                 ,  'Y', 'T'                  ,'Out Of State Travel' ),
	( 'TEXTANNOT'         ,  'Y', 'TEXTANNOT'          ,'Text Annotation' ),
	( 'TN'                ,  'Y', 'TN'                 ,'Lobby Termination Notice' );
	-- ( 'UNKNOWN'           ,  'Y', 'UNKNOWN'            ,'Unknown' );
